FORMAT: 1A
HOST: http://polls.apiblueprint.org/

#Test-Connect-GitHub

## Data Structures

### BaseObject (object)
+ id: `d3594396-d546-4326-a252-733fa6ebe57a` (string, required)
+ dateCreated: `2020-01-01T23:58:45Z` (string, required)
+ dateUpdated: `2020-01-01T23:58:45Z` (string, required)
+ createdBy: `d3594396-d546-4326-a252-733fa6ebe57a` (string, optional)
+ updatedBy: `d3594396-d546-4326-a252-733fa6ebe57a` (string, optional)
+ source: `prime` (string, required)
+ effectiveDate: `2020-01-01T23:58:45Z` (string, optional)
+ expiryDate: `2022-01-01T23:58:45Z` (string, optional)
+ entityType: `object` (string, required)
+ isSummary: `false` (boolean)